# Generated by Django 5.1.3 on 2024-11-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_styles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstyle',
            name='abvmax',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='abvmin',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='fgmax',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='fgmin',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ibumax',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ibumin',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ogmax',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ogmin',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='srmmax',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='srmmin',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
