# Generated by Django 5.1.3 on 2024-11-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_styles', '0002_alter_beerstyle_abvmax_alter_beerstyle_abvmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstyle',
            name='abvmax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='abvmin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='appearance_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='aroma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='aroma_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='characteristicingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='comments_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='commercialexamples',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='currentlydefinedtypes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='entryinstructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='entryinstructions_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='fgmax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='fgmin',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='flavor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='flavor_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ibumax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ibumin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='mouthfeel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='mouthfeel_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ogmax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ogmin',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='overallimpression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='overallimpression_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='srmmax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='srmmin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='strengthclassifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='stylecomparison',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
