# Generated by Django 5.1.3 on 2024-11-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_styles', '0003_alter_beerstyle_abvmax_alter_beerstyle_abvmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerstyle',
            name='entryinstructions_cz',
        ),
    ]
