# Generated by Django 5.1.3 on 2024-11-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_styles', '0004_remove_beerstyle_entryinstructions_cz'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerstyle',
            name='characteristicingredients_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='commercialexamples_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='currentlydefinedtypes_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='entryinstructions_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='history_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='strengthclassifications_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='stylecomparison_cz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='tags_cz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
